import os
import transliterate
from glob import glob
from json import dumps
import re
regex = r": \"(.*)\""
subst = ": \\1"
lines = {}
with open("index.js", 'w', encoding='utf-8') as f:
    f.write("// THIS IS AUTOMATICALLY GENERATED BY CREATE_LINES.PY\n")
    os.chdir("assets")
    for icon in glob("*.svg"):
        line = icon.replace(".svg", "")
        lines[line] = "line" + \
            (line if line.isdigit() else transliterate.translit(
                line, 'ru', reversed=True))
        print(icon, lines[line])
        f.write(
            f'import {lines[line]} from "./assets/{icon}"\n')
    f.write("export const metroIcons = ")
    f.write(re.sub(regex, subst, dumps(lines, ensure_ascii=False, indent=4)))
    f.write("\nexport * as metroLineNames from \"./lines.json\"")
